version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build images
          command: ./build.sh
